# Generated by Django 4.2.11 on 2024-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50, verbose_name='Device')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('type', models.CharField(choices=[('BLOOD_PRESSURE', 'Blood Pressure'), ('HEART_RATE', 'Heart Rate')], max_length=20, verbose_name='Version')),
            ],
        ),
    ]
